# Generated by Django 4.1.7 on 2023-03-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Id', models.IntegerField()),
                ('Vehicle_Number', models.CharField(max_length=10)),
                ('Vehicle_Type', models.CharField(max_length=20)),
                ('Vehicle_Model', models.CharField(max_length=50)),
                ('Vehicle_Description', models.TextField()),
            ],
        ),
    ]
