# Generated by Django 4.1.7 on 2023-03-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VMS_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='Vehicle_Id',
        ),
    ]
