# Generated by Django 4.1.7 on 2023-03-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS_app', '0002_remove_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_Type',
            field=models.CharField(choices=[('two', 'Two Wheeler'), ('three', 'Three Wheeler'), ('four', 'Four Wheeler')], max_length=20),
        ),
    ]
